services:
  web:
    container_name: todo-web
    build:
      context: ./container/web/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./container/web/conf.d:/etc/nginx/conf.d
      - ./container/web/ssl:/etc/nginx/ssl
  backend:
    container_name: todo-backend
    build:
      context: ./container/backend/
      dockerfile: ./Dockerfile
    volumes:
      - ./container/backend/src:/src
    tty: true
  frontend:
    container_name: todo-frontend
    build:
      context: ./container/frontend/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./container/frontend/src:/src
      - node_modules:/src/node_modules
    tty: true
volumes:
  node_modules:
